{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Convert Keras model to Tensorflow model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "PermissionDeniedError",
     "evalue": "./model/tensorflow/model1.data-00000-of-00001.tempstate1458345464240017155; Permission denied\n\t [[node save/SaveV2 (defined at <ipython-input-1-ea323c614868>:13)  = SaveV2[dtypes=[DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, SGD/decay/Read/ReadVariableOp/_155, SGD/iterations/Read/ReadVariableOp/_157, SGD/lr/Read/ReadVariableOp/_159, SGD/momentum/Read/ReadVariableOp/_161, conv2d/bias/Read/ReadVariableOp/_163, conv2d/kernel/Read/ReadVariableOp/_165, conv2d_1/bias/Read/ReadVariableOp/_167, conv2d_1/kernel/Read/ReadVariableOp/_169, dense/bias/Read/ReadVariableOp/_171, dense/kernel/Read/ReadVariableOp/_173, input_tensor/bias/Read/ReadVariableOp/_175, input_tensor/kernel/Read/ReadVariableOp/_177, output_tensor/bias/Read/ReadVariableOp/_179, output_tensor/kernel/Read/ReadVariableOp/_181, training/SGD/Variable/Read/ReadVariableOp/_183, training/SGD/Variable_1/Read/ReadVariableOp/_185, training/SGD/Variable_2/Read/ReadVariableOp/_187, training/SGD/Variable_3/Read/ReadVariableOp/_189, training/SGD/Variable_4/Read/ReadVariableOp/_191, training/SGD/Variable_5/Read/ReadVariableOp/_193, training/SGD/Variable_6/Read/ReadVariableOp/_195, training/SGD/Variable_7/Read/ReadVariableOp/_197, training/SGD/Variable_8/Read/ReadVariableOp/_199, training/SGD/Variable_9/Read/ReadVariableOp/_201)]]\n\nCaused by op 'save/SaveV2', defined at:\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/__main__.py\", line 3, in <module>\n    app.launch_new_instance()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n    app.start()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/kernelapp.py\", line 499, in start\n    self.io_loop.start()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tornado/platform/asyncio.py\", line 132, in start\n    self.asyncio_loop.run_forever()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/asyncio/base_events.py\", line 421, in run_forever\n    self._run_once()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/asyncio/base_events.py\", line 1425, in _run_once\n    handle._run()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/asyncio/events.py\", line 127, in _run\n    self._callback(*self._args)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tornado/platform/asyncio.py\", line 122, in _handle_events\n    handler_func(fileobj, events)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py\", line 450, in _handle_events\n    self._handle_recv()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py\", line 480, in _handle_recv\n    self._run_callback(callback, msg)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py\", line 432, in _run_callback\n    callback(*args, **kwargs)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 283, in dispatcher\n    return self.dispatch_shell(stream, msg)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 233, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 399, in execute_request\n    user_expressions, allow_stdin)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/ipkernel.py\", line 208, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/zmqshell.py\", line 537, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2662, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2785, in _run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2901, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-1-ea323c614868>\", line 13, in <module>\n    saver = tf.train.Saver()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 1102, in __init__\n    self.build()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 1114, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 1151, in _build\n    build_save=build_save, build_restore=build_restore)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 792, in _build_internal\n    save_tensor = self._AddSaveOps(filename_tensor, saveables)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 284, in _AddSaveOps\n    save = self.save_op(filename_tensor, saveables)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 202, in save_op\n    tensors)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py\", line 1690, in save_v2\n    shape_and_slices=shape_and_slices, tensors=tensors, name=name)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py\", line 488, in new_func\n    return func(*args, **kwargs)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/framework/ops.py\", line 3274, in create_op\n    op_def=op_def)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/framework/ops.py\", line 1770, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nPermissionDeniedError (see above for traceback): ./model/tensorflow/model1.data-00000-of-00001.tempstate1458345464240017155; Permission denied\n\t [[node save/SaveV2 (defined at <ipython-input-1-ea323c614868>:13)  = SaveV2[dtypes=[DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, SGD/decay/Read/ReadVariableOp/_155, SGD/iterations/Read/ReadVariableOp/_157, SGD/lr/Read/ReadVariableOp/_159, SGD/momentum/Read/ReadVariableOp/_161, conv2d/bias/Read/ReadVariableOp/_163, conv2d/kernel/Read/ReadVariableOp/_165, conv2d_1/bias/Read/ReadVariableOp/_167, conv2d_1/kernel/Read/ReadVariableOp/_169, dense/bias/Read/ReadVariableOp/_171, dense/kernel/Read/ReadVariableOp/_173, input_tensor/bias/Read/ReadVariableOp/_175, input_tensor/kernel/Read/ReadVariableOp/_177, output_tensor/bias/Read/ReadVariableOp/_179, output_tensor/kernel/Read/ReadVariableOp/_181, training/SGD/Variable/Read/ReadVariableOp/_183, training/SGD/Variable_1/Read/ReadVariableOp/_185, training/SGD/Variable_2/Read/ReadVariableOp/_187, training/SGD/Variable_3/Read/ReadVariableOp/_189, training/SGD/Variable_4/Read/ReadVariableOp/_191, training/SGD/Variable_5/Read/ReadVariableOp/_193, training/SGD/Variable_6/Read/ReadVariableOp/_195, training/SGD/Variable_7/Read/ReadVariableOp/_197, training/SGD/Variable_8/Read/ReadVariableOp/_199, training/SGD/Variable_9/Read/ReadVariableOp/_201)]]\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mPermissionDeniedError\u001b[0m                     Traceback (most recent call last)",
      "\u001b[0;32m~/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n\u001b[1;32m   1333\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1334\u001b[0;31m       \u001b[0;32mreturn\u001b[0m \u001b[0mfn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1335\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mOpError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_run_fn\u001b[0;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n\u001b[1;32m   1318\u001b[0m       return self._call_tf_sessionrun(\n\u001b[0;32m-> 1319\u001b[0;31m           options, feed_dict, fetch_list, target_list, run_metadata)\n\u001b[0m\u001b[1;32m   1320\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_call_tf_sessionrun\u001b[0;34m(self, options, feed_dict, fetch_list, target_list, run_metadata)\u001b[0m\n\u001b[1;32m   1406\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_session\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moptions\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeed_dict\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfetch_list\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtarget_list\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1407\u001b[0;31m         run_metadata)\n\u001b[0m\u001b[1;32m   1408\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mPermissionDeniedError\u001b[0m: ./model/tensorflow/model1.data-00000-of-00001.tempstate1458345464240017155; Permission denied\n\t [[{{node save/SaveV2}} = SaveV2[dtypes=[DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, SGD/decay/Read/ReadVariableOp/_155, SGD/iterations/Read/ReadVariableOp/_157, SGD/lr/Read/ReadVariableOp/_159, SGD/momentum/Read/ReadVariableOp/_161, conv2d/bias/Read/ReadVariableOp/_163, conv2d/kernel/Read/ReadVariableOp/_165, conv2d_1/bias/Read/ReadVariableOp/_167, conv2d_1/kernel/Read/ReadVariableOp/_169, dense/bias/Read/ReadVariableOp/_171, dense/kernel/Read/ReadVariableOp/_173, input_tensor/bias/Read/ReadVariableOp/_175, input_tensor/kernel/Read/ReadVariableOp/_177, output_tensor/bias/Read/ReadVariableOp/_179, output_tensor/kernel/Read/ReadVariableOp/_181, training/SGD/Variable/Read/ReadVariableOp/_183, training/SGD/Variable_1/Read/ReadVariableOp/_185, training/SGD/Variable_2/Read/ReadVariableOp/_187, training/SGD/Variable_3/Read/ReadVariableOp/_189, training/SGD/Variable_4/Read/ReadVariableOp/_191, training/SGD/Variable_5/Read/ReadVariableOp/_193, training/SGD/Variable_6/Read/ReadVariableOp/_195, training/SGD/Variable_7/Read/ReadVariableOp/_197, training/SGD/Variable_8/Read/ReadVariableOp/_199, training/SGD/Variable_9/Read/ReadVariableOp/_201)]]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mPermissionDeniedError\u001b[0m                     Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-1-ea323c614868>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0msaver\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtrain\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSaver\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0msess\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mkeras\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbackend\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_session\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 15\u001b[0;31m \u001b[0msave_path\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0msaver\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msave\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msess\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mMODEL_PATH\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     16\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     17\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Keras model is successfully converted to TF model in \"\u001b[0m\u001b[0;34m+\u001b[0m\u001b[0mMODEL_PATH\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\u001b[0m in \u001b[0;36msave\u001b[0;34m(self, sess, save_path, global_step, latest_filename, meta_graph_suffix, write_meta_graph, write_state, strip_default_attrs)\u001b[0m\n\u001b[1;32m   1439\u001b[0m           model_checkpoint_path = sess.run(\n\u001b[1;32m   1440\u001b[0m               \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msaver_def\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msave_tensor_name\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1441\u001b[0;31m               {self.saver_def.filename_tensor_name: checkpoint_file})\n\u001b[0m\u001b[1;32m   1442\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1443\u001b[0m         \u001b[0mmodel_checkpoint_path\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcompat\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mas_str\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodel_checkpoint_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m    927\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    928\u001b[0m       result = self._run(None, fetches, feed_dict, options_ptr,\n\u001b[0;32m--> 929\u001b[0;31m                          run_metadata_ptr)\n\u001b[0m\u001b[1;32m    930\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0mrun_metadata\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    931\u001b[0m         \u001b[0mproto_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mTF_GetBuffer\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrun_metadata_ptr\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_run\u001b[0;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m   1150\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mfinal_fetches\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0mfinal_targets\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mhandle\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mfeed_dict_tensor\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1151\u001b[0m       results = self._do_run(handle, final_targets, final_fetches,\n\u001b[0;32m-> 1152\u001b[0;31m                              feed_dict_tensor, options, run_metadata)\n\u001b[0m\u001b[1;32m   1153\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1154\u001b[0m       \u001b[0mresults\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_run\u001b[0;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m   1326\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mhandle\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1327\u001b[0m       return self._do_call(_run_fn, feeds, fetches, targets, options,\n\u001b[0;32m-> 1328\u001b[0;31m                            run_metadata)\n\u001b[0m\u001b[1;32m   1329\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1330\u001b[0m       \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_do_call\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_prun_fn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mhandle\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeeds\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfetches\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n\u001b[1;32m   1346\u001b[0m           \u001b[0;32mpass\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1347\u001b[0m       \u001b[0mmessage\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0merror_interpolation\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minterpolate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmessage\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_graph\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1348\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnode_def\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mop\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmessage\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1349\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1350\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0m_extend_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mPermissionDeniedError\u001b[0m: ./model/tensorflow/model1.data-00000-of-00001.tempstate1458345464240017155; Permission denied\n\t [[node save/SaveV2 (defined at <ipython-input-1-ea323c614868>:13)  = SaveV2[dtypes=[DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, SGD/decay/Read/ReadVariableOp/_155, SGD/iterations/Read/ReadVariableOp/_157, SGD/lr/Read/ReadVariableOp/_159, SGD/momentum/Read/ReadVariableOp/_161, conv2d/bias/Read/ReadVariableOp/_163, conv2d/kernel/Read/ReadVariableOp/_165, conv2d_1/bias/Read/ReadVariableOp/_167, conv2d_1/kernel/Read/ReadVariableOp/_169, dense/bias/Read/ReadVariableOp/_171, dense/kernel/Read/ReadVariableOp/_173, input_tensor/bias/Read/ReadVariableOp/_175, input_tensor/kernel/Read/ReadVariableOp/_177, output_tensor/bias/Read/ReadVariableOp/_179, output_tensor/kernel/Read/ReadVariableOp/_181, training/SGD/Variable/Read/ReadVariableOp/_183, training/SGD/Variable_1/Read/ReadVariableOp/_185, training/SGD/Variable_2/Read/ReadVariableOp/_187, training/SGD/Variable_3/Read/ReadVariableOp/_189, training/SGD/Variable_4/Read/ReadVariableOp/_191, training/SGD/Variable_5/Read/ReadVariableOp/_193, training/SGD/Variable_6/Read/ReadVariableOp/_195, training/SGD/Variable_7/Read/ReadVariableOp/_197, training/SGD/Variable_8/Read/ReadVariableOp/_199, training/SGD/Variable_9/Read/ReadVariableOp/_201)]]\n\nCaused by op 'save/SaveV2', defined at:\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/__main__.py\", line 3, in <module>\n    app.launch_new_instance()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n    app.start()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/kernelapp.py\", line 499, in start\n    self.io_loop.start()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tornado/platform/asyncio.py\", line 132, in start\n    self.asyncio_loop.run_forever()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/asyncio/base_events.py\", line 421, in run_forever\n    self._run_once()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/asyncio/base_events.py\", line 1425, in _run_once\n    handle._run()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/asyncio/events.py\", line 127, in _run\n    self._callback(*self._args)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tornado/platform/asyncio.py\", line 122, in _handle_events\n    handler_func(fileobj, events)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py\", line 450, in _handle_events\n    self._handle_recv()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py\", line 480, in _handle_recv\n    self._run_callback(callback, msg)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py\", line 432, in _run_callback\n    callback(*args, **kwargs)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tornado/stack_context.py\", line 300, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 283, in dispatcher\n    return self.dispatch_shell(stream, msg)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 233, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 399, in execute_request\n    user_expressions, allow_stdin)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/ipkernel.py\", line 208, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/ipykernel/zmqshell.py\", line 537, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2662, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2785, in _run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2901, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-1-ea323c614868>\", line 13, in <module>\n    saver = tf.train.Saver()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 1102, in __init__\n    self.build()\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 1114, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 1151, in _build\n    build_save=build_save, build_restore=build_restore)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 792, in _build_internal\n    save_tensor = self._AddSaveOps(filename_tensor, saveables)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 284, in _AddSaveOps\n    save = self.save_op(filename_tensor, saveables)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/training/saver.py\", line 202, in save_op\n    tensors)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py\", line 1690, in save_v2\n    shape_and_slices=shape_and_slices, tensors=tensors, name=name)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py\", line 488, in new_func\n    return func(*args, **kwargs)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/framework/ops.py\", line 3274, in create_op\n    op_def=op_def)\n  File \"/home/cvrc/.conda/envs/TF1120_GPU/lib/python3.5/site-packages/tensorflow/python/framework/ops.py\", line 1770, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nPermissionDeniedError (see above for traceback): ./model/tensorflow/model1.data-00000-of-00001.tempstate1458345464240017155; Permission denied\n\t [[node save/SaveV2 (defined at <ipython-input-1-ea323c614868>:13)  = SaveV2[dtypes=[DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, SGD/decay/Read/ReadVariableOp/_155, SGD/iterations/Read/ReadVariableOp/_157, SGD/lr/Read/ReadVariableOp/_159, SGD/momentum/Read/ReadVariableOp/_161, conv2d/bias/Read/ReadVariableOp/_163, conv2d/kernel/Read/ReadVariableOp/_165, conv2d_1/bias/Read/ReadVariableOp/_167, conv2d_1/kernel/Read/ReadVariableOp/_169, dense/bias/Read/ReadVariableOp/_171, dense/kernel/Read/ReadVariableOp/_173, input_tensor/bias/Read/ReadVariableOp/_175, input_tensor/kernel/Read/ReadVariableOp/_177, output_tensor/bias/Read/ReadVariableOp/_179, output_tensor/kernel/Read/ReadVariableOp/_181, training/SGD/Variable/Read/ReadVariableOp/_183, training/SGD/Variable_1/Read/ReadVariableOp/_185, training/SGD/Variable_2/Read/ReadVariableOp/_187, training/SGD/Variable_3/Read/ReadVariableOp/_189, training/SGD/Variable_4/Read/ReadVariableOp/_191, training/SGD/Variable_5/Read/ReadVariableOp/_193, training/SGD/Variable_6/Read/ReadVariableOp/_195, training/SGD/Variable_7/Read/ReadVariableOp/_197, training/SGD/Variable_8/Read/ReadVariableOp/_199, training/SGD/Variable_9/Read/ReadVariableOp/_201)]]\n"
     ]
    }
   ],
   "source": [
    "# import the needed libraries\n",
    "import tensorflow as tf\n",
    "tf.keras.backend.set_learning_phase(0) #use this if we have batch norm layer in our network\n",
    "from tensorflow.keras.models import load_model\n",
    "\n",
    "# path we wanna save our converted TF-model\n",
    "MODEL_PATH = \"./model/tensorflow/model1\"\n",
    "\n",
    "# load the Keras model\n",
    "model = load_model('./model/modelLeNet5.h5')\n",
    "\n",
    "# save the model to Tensorflow model\n",
    "saver = tf.train.Saver()\n",
    "sess = tf.keras.backend.get_session()\n",
    "save_path = saver.save(sess, MODEL_PATH)\n",
    "\n",
    "print(\"Keras model is successfully converted to TF model in \"+MODEL_PATH)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Keras to TensorRT\n",
    "![alt text](pictures/Keras_to_TensorRT.png)\n",
    "\n",
    "### Tensorflow to TensorRT\n",
    "![alt text](pictures/tf-trt_workflow.png)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:TF1120_GPU]",
   "language": "python",
   "name": "conda-env-TF1120_GPU-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
